INSERT INTO `article` (`name`, `detail`, `description`, `manufacturing`, `price`, `reduction`, `genders`, `id_category`) VALUES
("Sneaker B30", "Maille et tissu technique bleus", "Désormais incontournable de la Maison, la sneaker B30 basse se distingue par sa silhouette athlétique et très actuelle. Confectionnée en maille et tissu technique bleus, elle est sublimée par la signature CD30 ton sur ton réfléchissante, revisitée dans un esprit graphique. La B30 affiche également les signatures Dior B30 et CD30 argentées sur la languette et à l'arrière. Une semelle sculptée en gomme bleue avec un liseré jaune fluo, rehaussée de nombreux détails emblématiques et un élastique intérieur, garantit un confort optimum. La sneaker B30 complètera toutes vos tenues casual.","Fabriquée en Italie", 950.00, 0, "homme", 1),
("Collier pendentif plaque CD Diamond", "Laiton argenté vieilli", "Nouveauté de la saison été 2024, le collier dévoile une inspiration militaire revisitée dans un esprit moderne. Les épais maillons forçat en laiton vieilli finition argentée se complètent d'un pendentif plaque gravé de signatures CD Diamond. Un fermoir ajustable sublimé par une signature CD Icon permettra de le porter de plusieurs longueurs différentes. Ce collier pourra être coordonné aux autres créations CD Diamond de la saison.", "Fabriqué en Allemagne", 650.00, 10, "homme", 2),
("Polo Dior Oblique", "Jacquard de coton blanc, bleu et marron", "Le polo en maille met à l'honneur l'emblématique motif Dior Oblique de la Maison. Confectionné en jacquard de coton blanc, bleu et marron, il présente une coupe droite complétée d'une fermeture boutonnée et de finitions côtelées. Ce polo rehaussera toutes vos tenues d'une touche graphique.", "Fabriqué en Italie", 1250.00, 0, "homme", 3),
("Casquette Christian Dior Couture", "Toile de coton technique gris et orange fluo", "La casquette propose une silhouette intemporelle. Confectionnée en toile de coton technique gris, elle présente des détails en cuir ton sur ton et une broderie Christian Dior Couture orange fluo sur le devant. Moderne et décontractée, cette casquette rehaussera toutes vos tenues casual.", "Fabriqué en Italie", 550.00, 5, "homme", 4),
("Skater B9S – ÉDITION LIMITÉE ET NUMÉROTÉE", "Cuir Kumo Cannage gris Dior", "La skater B9S s'inspire des codes skate et de l'esprit couture de la Maison. Confectionnée en cuir Kumo Cannage gris Dior, elle revisite le motif emblématique dans une version matelassée. La languette matelassée et la chaussette de maintien en tissu technique offrent un confort optimal. La signature Dior s'invite sur le talon et la languette, tandis que l'avant s'habille d'un empiècement en gomme ton sur ton à motif Cannage. Complétée d'une semelle en gomme gravée du motif Dior Oblique dégradé, cette skater apportera une touche couture à tous les looks. La paire est dotée d'une puce NFC sécurisée, placée sous la semelle avant du pied droit, et permettant d'accéder à une plateforme pour obtenir son certificat digital d'authenticité. Les détenteurs du certificat bénéficieront d'informations sur les lancements des futures collections.", "Fabriqué en Italie", 2000.00, 15, "homme", 5),
("Sac à dos Rider", "Toile jacquard Dior Oblique kaki", "Le sac à dos Rider possède des lignes simples qui rappellent le modèle écolier. Il est cependant remis au goût du jour, travaillé en toile jacquard kaki recouverte du motif Dior Oblique. Une fermeture zippée bidirectionnelle, une large poche zippée à l'avant et des bretelles matelassées et ajustables sont autant de détails nécessaires à votre vie quotidienne.", "Fabriqué en Italie", 2250.00, 15, "homme", 5),
("Sac à dos à rabat Dior 8", "Toile jacquard Dior Oblique noir", "Nouveauté de la saison été 2024, le sac à dos à rabat Dior 8 célèbre l'esprit outdoor et la modernité de la Maison. Ce modèle est confectionné en toile jacquard Dior Oblique noir. Le compartiment principal, sublimé par un rabat à boucles Dior 8, pourra accueillir tous vos essentiels, tandis que la poche zippée à l'avant et les poches latérales en maille technique permettront d'accéder rapidement à vos clés ou vos écouteurs. Ce sac à dos fonctionnel sera la touche finale à toutes vos tenues.", "Fabriqué en Italie", 2800.00, 0, "homme", 5),
("Skater B9S – ÉDITION LIMITÉE ET NUMÉROTÉE", "Satin Kumo Cannage jaune fluo", "La skater B9S s'inspire des codes skate et de l'esprit couture de la Maison. Confectionnée en satin Kumo Cannage jaune fluo, elle revisite le motif emblématique dans une version matelassée. La languette matelassée et la chaussette de maintien en tissu technique offrent un confort optimal. La signature Dior s'invite sur le talon et la languette, tandis que l'avant s'habille d'un empiècement en gomme ton sur ton à motif Cannage. Complétée d'une semelle en gomme gravée du motif Dior Oblique dégradé, cette skater apportera une touche couture à tous les looks. La paire est dotée d'une puce NFC sécurisée, placée sous la semelle avant du pied droit, et permettant d'accéder à une plateforme pour obtenir son certificat digital d'authenticité. Les détenteurs du certificat bénéficieront d'informations sur les lancements des futures collections.", "Fabriqué en Italie", 2000.00, 5, "homme", 1),
("Dior3D S1I","Lunettes de soleil rectangulaires vert néon", "Présentées lors du défilé été 2024, les lunettes de soleil rectangulaires Dior3D S1I se distinguent par leur design innovant. Sublimée par la technologie de l'impression 3D, la monture vert néon ajourée se pare des lignes graphiques du Cannage, ainsi que d'une signature Dior en métal sur les branches. Les verres miroir verts complètent ce modèle au porter léger et confortable.", "Fabriqué en Italie", 500.00, 0, "homme", 6),
("Sneaker B30", "Maille et tissu technique beiges", "Désormais incontournable de la Maison, la sneaker B30 basse se distingue par sa silhouette athlétique et très actuelle. Confectionnée en maille et tissu technique beiges, elle est sublimée par la signature CD30 ton sur ton réfléchissante, revisitée dans un esprit graphique. La B30 affiche également les signatures Dior B30 et CD30 argentées sur la languette et à l'arrière. Une semelle sculptée en gomme ultralégère beige avec un liseré jaune fluo, rehaussée de nombreux détails emblématiques et un élastique intérieur, garantit un confort optimum. La sneaker B30 complètera toutes vos tenues casual.","Fabriquée en Italie", 950.00, 0, "homme", 1),
("Sweatshirt Bobby, coupe relax", "Molleton de coton écru","Nouveauté de la saison été 2024, le sweatshirt met à l'honneur le fidèle animal de compagnie de Monsieur Dior, qui a donné son nom à de nombreuses créations de la Maison au fil des années. Confectionné en molleton de coton écru, il est sublimé par une broderie Bobby, accompagnée de la signature Dior 1947, célébrant l'héritage Dior à travers une date clé dans l'histoire de la Maison. Avec sa coupe relax et son col rond côtelé, ce sweatshirt s'associera à toutes vos tenues casual.","Fabriquée en Italie", 1400.00, 0, "homme", 7),
("Veste coach, coupe relax", "Molleton de coton écru","Nouveauté de la saison été 2024, la veste coach se distingue par son allure sportswear. Confectionnée en denim de coton beige à chevrons, elle affiche un patch Dior sur le devant, ainsi qu'une broderie Christian Dior Couture inspirée des universités américaines au dos. Avec son look contemporain, cette veste coach complétera aisément une tenue workwear.","Fabriquée en Italie", 1900.00, 0, "homme", 8),
("Dior3D S1I","Lunettes de soleil rectangulaires grises", "Présentées lors du défilé été 2024, les lunettes de soleil rectangulaires Dior3D S1I se distinguent par leur design innovant. Sublimée par la technologie de l'impression 3D, la monture grise ajourée se pare des lignes graphiques du Cannage, ainsi que d'une signature Dior en métal sur les branches. Les verres brun sombre complètent ce modèle au porter léger et confortable.", "Fabriqué en Italie", 500.00, 0, "homme", 6),
("Bracelet à maillons CD Diamond","Laiton argenté vieilli", "Nouveauté de la saison été 2024, le bracelet en laiton vieilli finition argentée revisite les codes de la Maison dans un esprit graphique et moderne. Les épais maillons striés dévoilent une plaque gravée de signatures CD Diamond. Ce bracelet pourra être coordonné aux autres créations CD Diamond de la collection pour un total look Dior.", "Fabriqué en Allemagne", 550.00, 15, "homme", 10),
("Sneaker B30", "Maille et tissu technique rose pâle", "Désormais incontournable de la Maison, la sneaker B30 basse se distingue par sa silhouette athlétique et très actuelle. Confectionnée en maille et tissu technique rose pâle, elle est sublimée par la signature CD30 ton sur ton réfléchissante, revisitée dans un esprit graphique. La B30 affiche également les signatures Dior B30 et CD30 ton sur ton sur la languette et à l'arrière. Une semelle sculptée en gomme ultralégère ton sur ton avec un liseré bleu fluo, rehaussée de nombreux détails emblématiques et un élastique intérieur, garantit un confort optimum. La sneaker B30 complètera toutes vos tenues casual.","Fabriquée en Italie", 950.00, 0, "homme", 1),
("Blouson Cannage", "Toile de coton mélangé écrue", "Nouveauté de la saison été 2024, le blouson réinterprète les codes de la Maison à travers un regard contemporain. Confectionnée en toile de coton mélangé écrue, elle affiche une coupe moderne et met à l'honneur l'iconique motif Cannage all-over. Le col et la poche poitrine plaquée, ainsi que les finitions côtelées créent un jeu de matières et de textures sur cette création moderne. Ce blouson se portera avec un pantalon de la saison pour signer un look mode.", "Fabriqué en Italie", 3100.00, 0, "homme", 17),
("Portefeuille à deux volets Saddle", "Marqueterie de cuir de veau grainé kaki et toile jacquard Dior Oblique kaki", "Le portefeuille à deux volets Saddle est un accessoire raffiné, démontrant le savoir-faire de la Maison. Confectionné en marqueterie de cuir de veau grainé et de toile jacquard Dior Oblique kaki, soulignant les lignes iconiques Saddle, il présente un intérieur doté d'une double fente pour reçus, d'un double compartiment à billets, de quatre fentes pour cartes, ainsi que d'un compartiment à soufflet à bouton-pression pour monnaie. Sublimé par la signature Dior à l'avant, ce portefeuille à deux volets se glissera facilement dans vos poches et vos sacs.", "Fabriqué en Italie/Espagne", 540.00, 0, "homme", 12),
("Sweatshirt à capuche Dior Oblique, coupe relax", "Jacquard de coton éponge noir", "Le sweatshirt à capuche noir met à l'honneur l'emblématique motif Dior Oblique. Confectionné en jacquard de coton éponge noir, il présente une coupe relax très confortable. Doté de poches latérales fendues, ce sweatshirt à capuche s'associera à tous vos jeans ou pantalons de survêtement pour un look décontracté.", "Fabriqué en Italie/Espagne", 1800.00, 0, "homme", 7),
("Bracelet Cannage", "Laiton argenté vieilli et perles d'eau douce blanches", "Nouveauté de la saison été 2024, le bracelet dévoile un design raffiné aux accents emblématiques. Composée de perles en laiton vieilli finition argentée et de perles d'eau douce blanches, cette pièce se distingue par un détail gravé du motif Cannage déstructuré. Un fermoir ajustable rehaussé d'une signature CD Icon ajourée permettra de le porter de plusieurs longueurs différentes. Ce bracelet pourra être coordonné au collier assorti pour un total look Dior.", "Fabriqué en Allemagne", 550.00, 0, "homme", 9),
("Collier pendentif Cannage", "Laiton argenté et doré et pierre de marbre marron", "Nouveauté de la saison été 2024, le collier s'inscrit comme une pièce moderne inspirée des archives de la Maison. Confectionné en laiton argenté, il dévoile un charm CD Icon et un pendentif Cannage déstructuré ajouré en laiton finition dorée renfermant une pierre de marbre marron. Un fermoir ajustable sublimé par une signature CD Icon permettra de porter ce collier de plusieurs longueurs différentes. Ce collier pourra être coordonné aux autres créations de la saison.", "Fabriqué en Allemagne", 650.00, 0, "homme", 2),
("Bague Dior Lucky Charms", "Métal vieilli finition dorée et cristal bleu", "Nouveauté de la saison automne 2024, la bague Dior Lucky Charms revisite les symboles de la Maison pour signer une création moderne. L'anneau en métal vieilli finition dorée présente la signature CD, ainsi qu'une étoile dévoilant un cristal bleu. Cette bague riche en symboles pourra être associée aux autres créations de la ligne Dior Lucky Charms.", "Fabriqué en Europe", 290.00, 0, "femme", 10),
("Les boucles d'oreilles Dior Tribales", "Métal finition doré mat et perles en résine blanche", "elles se caractérisent par un design moderne et iconique. Ce modèle intemporel, en métal finition doré mat, se compose de deux perles emblématiques, la petite perle signée CD vient se poser à l'avant de l'oreille, tandis que la plus grande se dessine subtilement derrière le lobe. L'avant et l'arrière pourront se mélanger à d'autres Dior Tribales, créant ainsi une possibilité infinie de looks.", "Fabriqué en Italie", 410.00, 5, "femme", 11),
("Le bracelet Petit CD", "Métal finition dorée et cristaux argentés", "offre une allure élégante et épurée. Ce modèle est constitué d'une fine chaîne en métal finition dorée ponctuée d'un cristal et laissant apparaître la signature CD pavée de cristaux aux reflets argentés au centre. Ce bracelet moderne et féminin pourra être associé aux autres créations Petit CD.", "Fabriqué en Europe", 250.00, 0, "femme", 9),
("Set de bracelets Christian Dior", "Broderie noire et blanche, métal finition dorée et cristaux blancs", "Les bracelets Christian Dior se déclinent cette saison dans une version délicate et sophistiquée faisant écho à la ligne Lucky Charms de la collection. La signature Christian Dior se dessine sur la broderie noire et blanche, sublimée par de délicats cœurs et étoiles en métal finition dorée et ornés de cristaux blancs. Ces bracelets s'ajustent grâce à des cordelettes à pompons faits à la main et pourront être portés en toute occasion, seuls ou superposés.", "Fabriqué en Italie", 450.00, 0, "femme", 9),
("Carré 90 New York", "Twill de soie noir et écru", "Le carré dévoile l'imprimé New York, thème phare de la collection, mettant en scène la skyline new-yorkaise et la statue de la Liberté dans un esprit graphique. Confectionné en twill de soie noir et écru, ce modèle double face à bords contrastés et roulottés à la main est sublimé par la signature Christian Dior. Ce carré pourra être porté autour du cou ou noué sur la tête pour un total look Dior.", "Fabriqué en Italie", 490.00, 0, "femme", 13),
("Ceinture 30 Montaigne réversible", "100 % cuir de veau. Finitions en métal palladium", "Inspirée de l'emblématique sac éponyme, la ceinture 30 Montaigne se décline dans une version réversible à l'aide de son système pivotant. Confectionnée en cuir de veau lisse noir d'un côté et blanc de l'autre, elle est sublimée par la boucle iconique CD en métal finition palladium. Ce modèle est doté de deux passants amovibles que vous pourrez porter ton sur ton ou de manière contrastée. Soulignant la taille avec élégance, cet accessoire intemporel s'accordera parfaitement avec un jean, une jupe ou une robe.", "Fabriqué en Italie", 590.00, 0, "femme", 14),
("La visière D-Smash", "85 % coton, 15 % polypropylène", "Elle dévoile le motif Paris Allover, thème phare de la collection, mettant en scène le décor parisien et ses monuments dans un esprit graphique. Confectionné en coton mélangé entièrement brodé noir et blanc, ce modèle est sublimé par une bande de garniture ton sur ton brodée de la signature Christian Dior Paris. Cette visière ajustable apportera la touche finale à une tenue moderne et pourra être coordonnée aux autres créations Paris de la collection.", "Fabriqué en Italie", 590.00, 0, "femme", 4),
("DiorCannage A1U", "Monture en métal doré", "Les lunettes de soleil DiorCannage A1U s'invitent comme une création élégante, rehaussée de détails emblématiques. La monture de forme pilote en métal doré se distingue par un délicat travail de gravure sur les branches, dévoilant le motif Cannage et la signature CD. Complétées de verres bleus, ces lunettes apporteront une touche moderne et féminine à toutes vos tenues.", "Fabriqué en Italie", 430.00, 0, "femme", 6),
("DiorSignature S11I", "Monture en acétate noir", "Les lunettes de soleil DiorSignature S11I viennent enrichir la ligne désormais iconique de la Maison d'une forme carrée moderne et féminine. La monture en acétate noir dévoile la signature Christian Dior Paris rehaussée de lignes en métal ruthénium se prolongeant sur l'avant de la monture. Complétées de verres dégradés gris, ces lunettes de soleil modernes donneront un style résolument Dior à tous les looks.", "Fabriqué en Italie", 490.00, 0, "femme", 6),
("Porte-cartes Freesia Dior Jolie", "Cuir d'agneau Cannage noir", "Nouveauté de la saison automne 2024, le porte-cartes Freesia Dior Jolie signe la nouvelle ligne de la Maison et s'inscrit comme un accessoire élégant et fonctionnel. Confectionné en cuir d'agneau noir à coutures Cannage, il est sublimé par la signature CD ornée d'une perle. Doté de cinq fentes pour cartes, cet accessoire raffiné se glissera partout et se coordonnera aux autres créations de la ligne Dior Jolie.", "Fabriqué en Italie", 380.00, 0, "femme", 15),
("Sac Callisto Diorstar", "Cuir d'agneau Macrocannage noir", "Nouveauté de la saison automne 2024, le sac Callisto vient enrichir la ligne Diorstar d'un design demi-lune moderne et féminin. Confectionné en cuir d'agneau noir à coutures Macrocannage, son design est sublimé par une fermeture zippée ornée d'une médaille gravée de la signature Christian Dior Paris et d'une étoile, symbole phare de la Maison, tandis que le compartiment spacieux présente des fentes pour cartes. La chaîne à maillons CD ponctués de perles se dote d'un empiècement en cuir pour offrir un porter confortable à l'épaule.", "Fabriqué en Italie", 2200.00, 5, "femme", 16),
("Le Dior Book Tote", "Christian Dior Paris à l'avant", "Une création originale signée Maria Grazia Chiuri, Directrice Artistique de Christian Dior, est désormais un classique de la Maison. Imaginé pour contenir tous vos essentiels du quotidien, ce modèle medium est entièrement brodé du motif Paris blanc et noir, thème phare de la collection, mettant en scène la tour Eiffel dans un esprit graphique. Sublimé par la signature Christian Dior Paris à l'avant, ce cabas est un bel exemple du savoir-faire Dior et se portera main ou épaule.", "Fabriqué en Italie", 3000.00, 0, "femme", 16),
("Le sac Lady D-Sire My ABCDior", "Cuir de veau Maxicannage noir", "Il s'inspire des codes d'élégance de l'iconique Lady Dior, revisités à travers une allure souple et déstructurée offrant une allure urbaine. Le cuir de veau noir dévoile les surpiqûres Maxicannage, revisitant le motif iconique de la Maison. Ce modèle medium est sublimé par des charms D.I.O.R. en métal doré pâle illuminant sa silhouette. Doté d'une bandoulière qui peut être personnalisée en ajoutant des badges symboles, ce modèle unique pourra être porté à la main ou crossbody.", "Fabriqué en Italie", 5700.00, 0, "femme", 16),
("Escarpin slingback J'Adior", "Cuir de veau noir", "L'escarpin slingback J'Adior est un magnifique exemple du savoir-faire de la Maison. Confectionné avec passion dans les ateliers italiens Christian Dior, ce modèle se décline en cuir de veau noir. Le ruban bicolore brodé J'Adior et orné d'un nœud plat, ainsi que le talon virgule de 6,5 cm, signent cette création féminine et raffinée.", "Fabriqué en Italie", 990.00, 15, "femme", 1),
("La mule Dway", "Coton brodé et motif Paris Allover blanc et noir", "Une pièce emblématique et intemporelle, dévoile le motif Paris Allover blanc et noir, thème phare de la collection, mettant en scène le décor parisien et ses monuments dans un esprit graphique. La tige brodée de la signature Christian Dior Paris apporte une touche instantanément reconnaissable. Son design épuré permet de l'enfiler facilement pour compléter une tenue décontractée. Ce soulier pourra être coordonné aux autres créations Paris Allover de la collection.", "Fabriqué en Italie", 690.00, 0, "femme", 1),
("Sneaker D-Connect", "Tissu technique noir", "La sneaker D-Connect dévoile le motif Paris Allover blanc et noir, thème phare de la collection, mettant en scène le décor parisien et ses monuments dans un esprit graphique. Ce modèle en tissu technique se dote d'une semelle épaisse, de détails en gomme et d'un bout arrondi à découpes en cuir blanc. L'association de matières ponctuées de la signature Dior offre une allure très contemporaine à cette sneaker qui se coordonnera aux autres créations Paris Allover de la collection.", "Fabriqué en Italie", 920.00, 0, "femme", 1),
("Sneaker D-Connect", "Tissu technique imprimé du motif Paris Allover blanc et noir", "La sneaker D-Connect dévoile le motif Paris Allover blanc et noir, thème phare de la collection, mettant en scène le décor parisien et ses monuments dans un esprit graphique. Ce modèle en tissu technique se dote d'une semelle épaisse, de détails en gomme et d'un bout arrondi à découpes en cuir blanc. L'association de matières ponctuées de la signature Dior offre une allure très contemporaine à cette sneaker qui se coordonnera aux autres créations Paris Allover de la collection.", "Fabriqué en Italie", 920.00, 0, "femme", 1),
("Blouse", "Popeline de coton blanc", "La blouse en popeline de coton blanc revisite un classique intemporel. Ce modèle raffiné dévoile un col en pointe et des poignets mousquetaires accentuant son allure sophistiquée. Une abeille brodée et une signature CD subliment discrètement cette blouse qui se prêtera aussi bien à des tenues habillées que plus décontractées.", "Fabriqué en Italie", 1680.00, 10, "femme", 18),
("Le pull dévoile", "Maille de cachemire et soie à motif Paris noir et blanc","Le motif Paris noir et blanc, thème phare de la collection, mettant en scène la tour Eiffel dans un esprit graphique. Confectionné en maille de cachemire et soie, il se distingue par sa coupe droite et ses finitions côtelées, ainsi que sa signature Christian Dior dans le dos. Ce pull sublimera tous les looks au fil des saisons.", "Fabriqué en Italie", 2300.00, 0, "femme", 19),
("Pull Dioriviera", "Maille côtelée de coton écru","Issu de la capsule Dioriviera, le pull se distingue par sa coupe ajustée. Confectionné en maille côtelée de coton écru, il est rehaussé par un col marin signé Christian Dior et de bordures contrastées bleu marine au dos. Classique et moderne à la fois, ce pull s'associera aux autres créations Dioriviera pour un total look.", "Fabriqué en Italie", 1300.00, 0, "femme", 19);

INSERT INTO `image` (`img`, `id_article`) VALUES
('/images/Homme/Shoes/SneakerB30/Bleu/img_1', 1), ('/images/Homme/Shoes/SneakerB30/Bleu/img_2', 1), ('/images/Homme/Shoes/SneakerB30/Bleu/img_3', 1), ('/images/Homme/Shoes/SneakerB30/Bleu/img_4', 1), ('/images/Homme/Shoes/SneakerB30/Bleu/img_5', 1),
('/images/Homme/Accessories/Collier/Laiton_argente_vieilli/img_1', 2), ('/images/Homme/Accessories/Collier/Laiton_argente_vieilli/img_2', 2),
('/images/Homme/Tops/Polo/Blanc_bleu_marron/img_1', 3), ('/images/Homme/Tops/Polo/Blanc_bleu_marron/img_2', 3), ('/images/Homme/Tops/Polo/Blanc_bleu_marron/img_3', 3), ('/images/Homme/Tops/Polo/Blanc_bleu_marron/img_4', 3), ('/images/Homme/Tops/Polo/Blanc_bleu_marron/img_5', 3), ('/images/Homme/Tops/Polo/Blanc_bleu_marron/img_6', 3),
('/images/Homme/Accessories/Casquettes/Gris_Orange-fluo/img_1', 4), ('/images/Homme/Accessories/Casquettes/Gris_Orange-fluo/img_2', 4), ('/images/Homme/Accessories/Casquettes/Gris_Orange-fluo/img_3', 4), ('/images/Homme/Accessories/Casquettes/Gris_Orange-fluo/img_4', 4), ('/images/Homme/Accessories/Casquettes/Gris_Orange-fluo/img_5', 4), ('/images/Homme/Accessories/Casquettes/Gris_Orange-fluo/img_6', 4),
('/images/Homme/Shoes/SkaterB9S/Gris_Dior/img_1', 5), ('/images/Homme/Shoes/SkaterB9S/Gris_Dior/img_2', 5), ('/images/Homme/Shoes/SkaterB9S/Gris_Dior/img_3', 5), ('/images/Homme/Shoes/SkaterB9S/Gris_Dior/img_4', 5), ('/images/Homme/Shoes/SkaterB9S/Gris_Dior/img_5', 5), ('/images/Homme/Shoes/SkaterB9S/Gris_Dior/img_6', 5),
('/images/Homme/Bags/Rider/Kaki/img_1', 6), ('/images/Homme/Bags/Rider/Kaki/img_2', 6), ('/images/Homme/Bags/Rider/Kaki/img_3', 6), ('/images/Homme/Bags/Rider/Kaki/img_4', 6), ('/images/Homme/Bags/Rider/Kaki/img_5', 6),
('/images/Homme/Bags/Rabat/Noir/img_1', 7), ('/images/Homme/Bags/Rabat/Noir/img_2', 7), ('/images/Homme/Bags/Rabat/Noir/img_3', 7), ('/images/Homme/Bags/Rabat/Noir/img_4', 7), ('/images/Homme/Bags/Rabat/Noir/img_5', 7), ('/images/Homme/Bags/Rabat/Noir/img_6', 7), ('/images/Homme/Bags/Rabat/Noir/img_7', 7), ('/images/Homme/Bags/Rabat/Noir/img_8', 7),
('/images/Homme/Shoes/SkaterB9S/Jaune_Fluo/img_1', 8), ('/images/Homme/Shoes/SkaterB9S/Jaune_Fluo/img_2', 8), ('/images/Homme/Shoes/SkaterB9S/Jaune_Fluo/img_3', 8), ('/images/Homme/Shoes/SkaterB9S/Jaune_Fluo/img_4', 8), ('/images/Homme/Shoes/SkaterB9S/Jaune_Fluo/img_5', 8), ('/images/Homme/Shoes/SkaterB9S/Jaune_Fluo/img_6', 8), ('/images/Homme/Shoes/SkaterB9S/Jaune_Fluo/img_7', 8), ('/images/Homme/Shoes/SkaterB9S/Jaune_Fluo/img_8', 8),
('/images/Homme/Accessories/Lunettes/3D/Vert-neon/img_1', 9), ('/images/Homme/Accessories/Lunettes/3D/Vert-neon/img_2', 9), ('/images/Homme/Accessories/Lunettes/3D/Vert-neon/img_3', 9), ('/images/Homme/Accessories/Lunettes/3D/Vert-neon/img_4', 9), ('/images/Homme/Accessories/Lunettes/3D/Vert-neon/img_5', 9),
('/images/Homme/Shoes/SneakerB30/Beige/img_1', 10), ('/images/Homme/Shoes/SneakerB30/Beige/img_2', 10), ('/images/Homme/Shoes/SneakerB30/Beige/img_3', 10), ('/images/Homme/Shoes/SneakerB30/Beige/img_4', 10), ('/images/Homme/Shoes/SneakerB30/Beige/img_5', 10), ('/images/Homme/Shoes/SneakerB30/Beige/img_6', 10), ('/images/Homme/Shoes/SneakerB30/Beige/img_7', 10),
('/images/Homme/Tops/Sweatshirt/Bobby/img_1', 11), ('/images/Homme/Tops/Sweatshirt/Bobby/img_2', 11), ('/images/Homme/Tops/Sweatshirt/Bobby/img_3', 11), ('/images/Homme/Tops/Sweatshirt/Bobby/img_4', 11), ('/images/Homme/Tops/Sweatshirt/Bobby/img_5', 11), ('/images/Homme/Tops/Sweatshirt/Bobby/img_6', 11), ('/images/Homme/Tops/Sweatshirt/Bobby/img_7', 11),
('/images/Homme/Tops/Veste/Coach_coton-ecru/img_1', 12), ('/images/Homme/Tops/Veste/Coach_coton-ecru/img_2', 12), ('/images/Homme/Tops/Veste/Coach_coton-ecru/img_3', 12), ('/images/Homme/Tops/Veste/Coach_coton-ecru/img_4', 12), ('/images/Homme/Tops/Veste/Coach_coton-ecru/img_5', 12), ('/images/Homme/Tops/Veste/Coach_coton-ecru/img_6', 12), ('/images/Homme/Tops/Veste/Coach_coton-ecru/img_7', 12),
('/images/Homme/Accessories/Lunettes/3D/Gris/img_1', 13), ('/images/Homme/Accessories/Lunettes/3D/Gris/img_2', 13), ('/images/Homme/Accessories/Lunettes/3D/Gris/img_3', 13), ('/images/Homme/Accessories/Lunettes/3D/Gris/img_4', 13), ('/images/Homme/Accessories/Lunettes/3D/Gris/img_5', 13), ('/images/Homme/Accessories/Lunettes/3D/Gris/img_6', 13),
('/images/Homme/Accessories/Bracelet/Laiton_argente_vieilli/img_1', 14), ('/images/Homme/Accessories/Bracelet/Laiton_argente_vieilli/img_2', 14), ('/images/Homme/Accessories/Bracelet/Laiton_argente_vieilli/img_3', 14),
('/images/Homme/Shoes/SneakerB30/Rose_pale/img_1', 15), ('/images/Homme/Shoes/SneakerB30/Rose_pale/img_2', 15), ('/images/Homme/Shoes/SneakerB30/Rose_pale/img_3', 15), ('/images/Homme/Shoes/SneakerB30/Rose_pale/img_4', 15),
('/images/Homme/Tops/Veste/Cannage_coton-melanger-ecrue/img_1', 16), ('/images/Homme/Tops/Veste/Cannage_coton-melanger-ecrue/img_2', 16), ('/images/Homme/Tops/Veste/Cannage_coton-melanger-ecrue/img_3', 16), ('/images/Homme/Tops/Veste/Cannage_coton-melanger-ecrue/img_4', 16), ('/images/Homme/Tops/Veste/Cannage_coton-melanger-ecrue/img_5', 16), ('/images/Homme/Tops/Veste/Cannage_coton-melanger-ecrue/img_6', 16), ('/images/Homme/Tops/Veste/Cannage_coton-melanger-ecrue/img_7', 16),
('/images/Homme/Accessories/Porte-carte/Kaki/img_1', 17), ('/images/Homme/Accessories/Porte-carte/Kaki/img_2', 17), ('/images/Homme/Accessories/Porte-carte/Kaki/img_3', 17), ('/images/Homme/Accessories/Porte-carte/Kaki/img_4', 17), ('/images/Homme/Accessories/Porte-carte/Kaki/img_5', 17),
('/images/Homme/Tops/Sweatshirt/Capuche_Noir/img_1', 18), ('/images/Homme/Tops/Sweatshirt/Capuche_Noir/img_2', 18), ('/images/Homme/Tops/Sweatshirt/Capuche_Noir/img_3', 18), ('/images/Homme/Tops/Sweatshirt/Capuche_Noir/img_4', 18), ('/images/Homme/Tops/Sweatshirt/Capuche_Noir/img_5', 18), ('/images/Homme/Tops/Sweatshirt/Capuche_Noir/img_6', 18), ('/images/Homme/Tops/Sweatshirt/Capuche_Noir/img_7', 18),
('/images/Homme/Accessories/Bracelet/Cannage/img_1', 19), ('/images/Homme/Accessories/Bracelet/Cannage/img_2', 19), ('/images/Homme/Accessories/Bracelet/Cannage/img_3', 19),
('/images/Homme/Accessories/Collier/Cannage/img_1', 20), ('/images/Homme/Accessories/Collier/Cannage/img_2', 20),
('/images/Femme/Accessories/Bague/Lucky_Charms/img_1', 21), ('/images/Femme/Accessories/Bague/Lucky_Charms/img_2', 21), ('/images/Femme/Accessories/Bague/Lucky_Charms/img_3', 21),
('/images/Femme/Accessories/Boucles_doreilles/Dior_Tribales/img_1', 22), ('/images/Femme/Accessories/Boucles_doreilles/Dior_Tribales/img_2', 22), ('/images/Femme/Accessories/Boucles_doreilles/Dior_Tribales/img_3', 22), ('/images/Femme/Accessories/Boucles_doreilles/Dior_Tribales/img_4', 22),
('/images/Femme/Accessories/Bracelet/Petit_CD/img_1', 23), ('/images/Femme/Accessories/Bracelet/Petit_CD/img_2', 23),
('/images/Femme/Accessories/Bracelet/Set_de_bracelets/Noir_Blanc/img_1', 24), ('/images/Femme/Accessories/Bracelet/Set_de_bracelets/Noir_Blanc/img_2', 24), ('/images/Femme/Accessories/Bracelet/Set_de_bracelets/Noir_Blanc/img_3', 24),
('/images/Femme/Accessories/Carre/90_New-York/img_1', 25), ('/images/Femme/Accessories/Carre/90_New-York/img_2', 25), ('/images/Femme/Accessories/Carre/90_New-York/img_3', 25), ('/images/Femme/Accessories/Carre/90_New-York/img_4', 25), ('/images/Femme/Accessories/Carre/90_New-York/img_5', 25),
('/images/Femme/Accessories/Ceinture/30_Montaigne/img_1', 26), ('/images/Femme/Accessories/Ceinture/30_Montaigne/img_2', 26), ('/images/Femme/Accessories/Ceinture/30_Montaigne/img_3', 26), ('/images/Femme/Accessories/Ceinture/30_Montaigne/img_4', 26), ('/images/Femme/Accessories/Ceinture/30_Montaigne/img_5', 26), ('/images/Femme/Accessories/Ceinture/30_Montaigne/img_6', 26), ('/images/Femme/Accessories/Ceinture/30_Montaigne/img_7', 26),
('/images/Femme/Accessories/Chapeau/Visière/img_1', 27), ('/images/Femme/Accessories/Chapeau/Visière/img_2', 27), ('/images/Femme/Accessories/Chapeau/Visière/img_3', 27), ('/images/Femme/Accessories/Chapeau/Visière/img_4', 27), ('/images/Femme/Accessories/Chapeau/Visière/img_5', 27), ('/images/Femme/Accessories/Chapeau/Visière/img_6', 27),
('/images/Femme/Accessories/Lunettes/Cannage_A1U/img_1', 28), ('/images/Femme/Accessories/Lunettes/Cannage_A1U/img_2', 28), ('/images/Femme/Accessories/Lunettes/Cannage_A1U/img_3', 28), ('/images/Femme/Accessories/Lunettes/Cannage_A1U/img_4', 28),
('/images/Femme/Accessories/Lunettes/Signature_S11I/img_1', 29), ('/images/Femme/Accessories/Lunettes/Signature_S11I/img_2', 29), ('/images/Femme/Accessories/Lunettes/Signature_S11I/img_3', 29),
('/images/Femme/Accessories/Lunettes/Porte-carte/Freesia/img_1', 30), ('/images/Femme/Accessories/Lunettes/Porte-carte/Freesia/img_2', 30), ('/images/Femme/Accessories/Lunettes/Porte-carte/Freesia/img_3', 30),
('/images/Femme/Bags/Callisto_Diorstar/img_1', 31), ('/images/Femme/Bags/Callisto_Diorstar/img_2', 31), ('/images/Femme/Bags/Callisto_Diorstar/img_3', 31),
('/images/Femme/Bags/Dior_Book_Tote_Medium/img_1', 32), ('/images/Femme/Bags/Dior_Book_Tote_Medium/img_2', 32), ('/images/Femme/Bags/Dior_Book_Tote_Medium/img_3', 32),('/images/Femme/Bags/Dior_Book_Tote_Medium/img_4', 32), ('/images/Femme/Bags/Dior_Book_Tote_Medium/img_5', 32),
('/images/Femme/Bags/LadyD-Sire_My_ABCDior_Medium/img_1', 33), ('/images/Femme/Bags/LadyD-Sire_My_ABCDior_Medium/img_2', 33), ('/images/Femme/Bags/LadyD-Sire_My_ABCDior_Medium/img_3', 33),
('/images/Femme/Shoes/Escarpin_slingback_Adior/img_1', 34), ('/images/Femme/Shoes/Escarpin_slingback_Adior/img_2', 34), ('/images/Femme/Shoes/Escarpin_slingback_Adior/img_3', 34), ('/images/Femme/Shoes/Escarpin_slingback_Adior/img_4', 34), ('/images/Femme/Shoes/Escarpin_slingback_Adior/img_5', 34),
('/images/Femme/Shoes/Mule_Dway/img_1', 35), ('/images/Femme/Shoes/Mule_Dway/img_2', 35), ('/images/Femme/Shoes/Mule_Dway/img_3', 35), ('/images/Femme/Shoes/Mule_Dway/img_4', 35),
('/images/Femme/Shoes/SneakerD-Connect/Noir/img_1', 36), ('/images/Femme/Shoes/SneakerD-Connect/Noir/img_2', 36), ('/images/Femme/Shoes/SneakerD-Connect/Noir/img_3', 36), ('/images/Femme/Shoes/SneakerD-Connect/Noir/img_4', 36),
('/images/Femme/Shoes/SneakerD-Connect/Noir-blanc/img_1', 37), ('/images/Femme/Shoes/SneakerD-Connect/Noir-blanc/img_2', 37), ('/images/Femme/Shoes/SneakerD-Connect/Noir-blanc/img_3', 37), ('/images/Femme/Shoes/SneakerD-Connect/Noir-blanc/img_4', 37),
('/images/Femme/Tops/Blouse/Blanc/img_1', 38), ('/images/Femme/Tops/Blouse/Blanc/img_2', 38), ('/images/Femme/Tops/Blouse/Blanc/img_3', 38),
('/images/Femme/Tops/Pull/Brode/img_1', 39), ('/images/Femme/Tops/Pull/Brode/img_2', 39), ('/images/Femme/Tops/Pull/Brode/img_3', 39), ('/images/Femme/Tops/Pull/Brode/img_4', 39), ('/images/Femme/Tops/Pull/Brode/img_5', 39),
('/images/Femme/Tops/Pull/Dioriviera/img_1', 40), ('/images/Femme/Tops/Pull/Dioriviera/img_2', 40), ('/images/Femme/Tops/Pull/Dioriviera/img_3', 40), ('/images/Femme/Tops/Pull/Dioriviera/img_4', 40);

INSERT INTO `size` (`size`) VALUES
('36.5'),
('39'),
('39.5'),
('40'),
('40.5'),
('41'),
('41.5'),
('42'),
('42.5'),
('43'),
('43.5'),
('44'),
('45'),
('46'),
('47'),
('48'),
('50'),
('52'),
('54'),
('56'),
('58'),
('60'),
('XXS'),
('XS'),
('S'),
('M'),
('L'),
('XL'),
('XXL'),
('XXXL'),
('Taille unique');

INSERT INTO `have_sizes` (`id_article`, `id_size`, `stock`) VALUES
(1, 1, 4), (1, 2, 10), (1, 3, 6), (1, 4, 0), (1, 5, 9), (1, 6, 0), (1, 7, 0), (1, 8, 4), (1, 9, 6), (1, 10, 7), (1, 11, 0), (1, 12, 5), (1, 13, 8), (1, 14, 6), (1, 15, 7),
(2, 31, 6),
(3, 23, 7), (3, 24, 0), (3, 25, 0), (3, 26, 7), (3, 27, 0), (3, 28, 8), (3, 29, 19), (3, 30, 4),
(4, 31, 6),
(5, 1, 4), (5, 2, 10), (5, 3, 6), (5, 4, 0), (5, 5, 9), (5, 6, 0), (5, 7, 0), (5, 8, 4), (5, 9, 6), (5, 10, 7), (5, 11, 0), (5, 12, 5), (5, 13, 8), (5, 14, 6), (5, 15, 7),
(6, 31, 2),
(7, 31, 8),
(8, 1, 4), (8, 2, 10), (8, 3, 6), (8, 4, 0), (8, 5, 9), (8, 6, 0), (8, 7, 0), (8, 8, 4), (8, 9, 6), (8, 10, 7), (8, 11, 0), (8, 12, 5), (8, 13, 8), (8, 14, 6), (8, 15, 7),
(9, 31, 3),
(10, 1, 4), (10, 2, 10), (10, 3, 6), (10, 4, 0), (10, 5, 9), (10, 6, 0), (10, 7, 0), (10, 8, 4), (10, 9, 6), (10, 10, 7), (10, 11, 0), (10, 12, 5), (10, 13, 8), (10, 14, 6), (10, 15, 7),
(11, 23, 7), (11, 24, 0), (11, 25, 0), (11, 26, 7), (11, 27, 0), (11, 28, 8), (11, 29, 0), (11, 30, 4),
(12, 23, 7), (12, 24, 0), (12, 25, 0), (12, 26, 7), (12, 27, 0), (12, 28, 8), (12, 29, 0), (12, 30, 4),
(13, 31, 0),
(14, 31, 0),
(15, 1, 4), (15, 2, 10), (15, 3, 6), (15, 4, 0), (15, 5, 9), (15, 6, 0), (15, 7, 0), (15, 8, 4), (15, 9, 6), (15, 10, 7), (15, 11, 0), (15, 12, 5), (15, 13, 8), (15, 14, 6), (15, 15, 7),
(16, 23, 7), (16, 24, 0), (16, 25, 15), (16, 26, 7), (16, 27, 0), (16, 28, 8), (16, 29, 0), (16, 30, 4),
(17, 31, 0),
(18, 23, 7), (18, 24, 0), (18, 25, 0), (18, 26, 7), (18, 27, 0), (18, 28, 8), (18, 29, 0), (18, 30, 4),
(19, 31, 25),
(20, 31, 5),
(21, 31, 1),
(22, 31, 6),
(23, 31, 16),
(24, 31, 3),
(25, 31, 34),
(26, 31, 4),
(27, 31, 26),
(28, 31, 3),
(29, 31, 17),
(30, 31, 7),
(31, 31, 2),
(32, 31, 8),
(33, 31, 18),
(34, 1, 4), (34, 2, 10), (34, 3, 6), (34, 4, 0), (34, 5, 9), (34, 6, 0), (34, 7, 0), (34, 8, 4), (34, 9, 6), (34, 10, 7), (34, 11, 0), (34, 12, 5), (34, 13, 8), (34, 14, 6), (34, 15, 7),
(35, 1, 0), (35, 2, 1), (35, 3, 6), (35, 4, 0), (35, 5, 9), (35, 6, 0), (35, 7, 0), (35, 8, 0), (35, 9, 6), (35, 10, 7), (35, 11, 0), (35, 12, 5), (35, 13, 8), (35, 14, 6), (35, 15, 7),
(36, 1, 10), (36, 2, 1), (36, 3, 6), (36, 4, 0), (36, 5, 9), (36, 6, 0), (36, 7, 0), (36, 8, 0), (36, 9, 6), (36, 10, 7), (36, 11, 0), (36, 12, 5), (36, 13, 8), (36, 14, 6), (36, 15, 7),
(37, 1, 10), (37, 2, 1), (37, 3, 6), (37, 4, 0), (37, 5, 9), (37, 6, 0), (37, 7, 0), (37, 8, 0), (37, 9, 6), (37, 10, 7), (37, 11, 0), (37, 12, 5), (37, 13, 8), (37, 14, 6), (37, 15, 7),
(38, 14, 2), (38, 15, 2), (38, 16, 0), (38, 17, 9), (38, 18, 0), (38, 19, 3), (38, 20, 0), (38, 21, 24), (38, 22, 25),
(39, 23, 7), (39, 24, 0), (39, 25, 0), (39, 26, 7), (39, 27, 0), (39, 28, 8), (39, 29, 19), (39, 30, 4),
(40, 23, 7), (40, 24, 0), (40, 25, 0), (40, 26, 7), (40, 27, 0), (40, 28, 0), (40, 29, 0), (40, 30, 4);


INSERT INTO `color` (`color`) VALUES
('Bleu'),
('Argenté'),
('Blanc'),
('Marron'),
('Gris'),
('Orange'),
('Kaki'),
('Noir'),
('Jaune'),
('Vert'),
('Beige'),
('Écru'),
('Rose'),
('Doré');

INSERT INTO `have_colors` (`id_article`, `id_color`) VALUES
(1, 1),
(2, 2),
(3, 1), (3, 3), (3, 4),
(4, 5), (4, 6),
(5, 5),
(6, 7),
(7, 7),
(8, 8),
(9, 9),
(10, 10),
(11, 11),
(12, 11),
(13, 5),
(14, 2),
(15, 13),
(16, 12),
(17, 7),
(18, 8),
(19, 2), (19, 3),
(20, 2), (20, 4),
(21, 1),
(22, 14), (22, 3),
(23, 14), (23, 2),
(24, 8), (24, 3), (24, 14),
(25, 8), (25, 12),
(26, 8), (26, 3),
(27, 8), (27, 3),
(28, 14),
(29, 8),
(30, 8),
(31, 8),
(32, 8), (32, 3),
(33, 8),
(34, 8),
(35, 8), (35, 3),
(36, 8),
(37, 3), (37, 8),
(38, 3),
(39, 8), (39, 3),
(40, 12);

INSERT INTO `material` (`material`) VALUES
('Maille'),
('Tissu'),
('Coton'),
('Cuir'),
('Toile'),
('Satin'),
('Plastique'),
('Laiton'),
('Perle'),
('Pierre de marbre'),
('Métal'),
('Cristal'),
('Broderie'),
('Soie'),
('Polypropylène'),
('Acétate');

INSERT INTO `have_materials` (`id_article`, `id_material`) VALUES
(1, 1), (1, 2),
(2, 8),
(3, 3),
(4, 3),
(5, 4),
(6, 5),
(7, 5),
(8, 6),
(9, 7),
(10, 1), (10, 2),
(11, 3),
(12, 3),
(13, 7),
(14, 8),
(15, 1), (15, 2),
(16, 3),
(17, 4), (17, 5),
(18, 3),
(19, 8), (19, 9),
(20, 8), (20, 10),
(21, 11), (21, 12),
(22, 11), (22, 9),
(23, 11), (23, 12),
(24, 13),
(25, 14),
(26, 4),
(27, 3), (27, 15),
(28, 11),
(29, 16),
(30, 4),
(31, 4),
(32, 13),
(33, 4),
(34, 3),
(35, 4),
(36, 2),
(37, 2),
(38, 3),
(39, 1), (39, 14),
(40, 3);

INSERT INTO `category` (`category`) VALUES
('Chaussures'),
('Colliers'),
('Polos'),
('Casquettes'),
('Sac à dos'),
('Lunettes'),
('Sweatshirts'),
('Vestes'),
('Bracelets'),
('Bagues'),
("Boucles d'oreille"),
('Portefeuilles'),
('Carré'),
('Ceintures'),
('Porte-cartes'),
('Sacs'),
('Blousons'),
('Blouses'),
('Pulls');